// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sensor.proto
// Protobuf C++ Version: 5.29.3

#include "sensor.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace sensor {

inline constexpr Value4Int32Request::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : device_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        action_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        op_1_{0},
        op_2_{0},
        op_3_{0},
        op_4_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Value4Int32Request::Value4Int32Request(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Value4Int32RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Value4Int32RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Value4Int32RequestDefaultTypeInternal() {}
  union {
    Value4Int32Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Value4Int32RequestDefaultTypeInternal _Value4Int32Request_default_instance_;

inline constexpr Value2Int32Request::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : device_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        action_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        op_1_{0},
        op_2_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Value2Int32Request::Value2Int32Request(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Value2Int32RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Value2Int32RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Value2Int32RequestDefaultTypeInternal() {}
  union {
    Value2Int32Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Value2Int32RequestDefaultTypeInternal _Value2Int32Request_default_instance_;

inline constexpr Value2DoubleRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : device_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        action_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        op_1_{0},
        op_2_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Value2DoubleRequest::Value2DoubleRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Value2DoubleRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Value2DoubleRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Value2DoubleRequestDefaultTypeInternal() {}
  union {
    Value2DoubleRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Value2DoubleRequestDefaultTypeInternal _Value2DoubleRequest_default_instance_;

inline constexpr GestureRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : device_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        action_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        op_1_{0},
        op_2_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GestureRequest::GestureRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GestureRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GestureRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GestureRequestDefaultTypeInternal() {}
  union {
    GestureRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GestureRequestDefaultTypeInternal _GestureRequest_default_instance_;
}  // namespace sensor
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_sensor_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_sensor_2eproto = nullptr;
const ::uint32_t
    TableStruct_sensor_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::sensor::GestureRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::sensor::GestureRequest, _impl_.device_id_),
        PROTOBUF_FIELD_OFFSET(::sensor::GestureRequest, _impl_.action_id_),
        PROTOBUF_FIELD_OFFSET(::sensor::GestureRequest, _impl_.op_1_),
        PROTOBUF_FIELD_OFFSET(::sensor::GestureRequest, _impl_.op_2_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::sensor::Value2DoubleRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::sensor::Value2DoubleRequest, _impl_.device_id_),
        PROTOBUF_FIELD_OFFSET(::sensor::Value2DoubleRequest, _impl_.action_id_),
        PROTOBUF_FIELD_OFFSET(::sensor::Value2DoubleRequest, _impl_.op_1_),
        PROTOBUF_FIELD_OFFSET(::sensor::Value2DoubleRequest, _impl_.op_2_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::sensor::Value2Int32Request, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::sensor::Value2Int32Request, _impl_.device_id_),
        PROTOBUF_FIELD_OFFSET(::sensor::Value2Int32Request, _impl_.action_id_),
        PROTOBUF_FIELD_OFFSET(::sensor::Value2Int32Request, _impl_.op_1_),
        PROTOBUF_FIELD_OFFSET(::sensor::Value2Int32Request, _impl_.op_2_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::sensor::Value4Int32Request, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::sensor::Value4Int32Request, _impl_.device_id_),
        PROTOBUF_FIELD_OFFSET(::sensor::Value4Int32Request, _impl_.action_id_),
        PROTOBUF_FIELD_OFFSET(::sensor::Value4Int32Request, _impl_.op_1_),
        PROTOBUF_FIELD_OFFSET(::sensor::Value4Int32Request, _impl_.op_2_),
        PROTOBUF_FIELD_OFFSET(::sensor::Value4Int32Request, _impl_.op_3_),
        PROTOBUF_FIELD_OFFSET(::sensor::Value4Int32Request, _impl_.op_4_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::sensor::GestureRequest)},
        {12, -1, -1, sizeof(::sensor::Value2DoubleRequest)},
        {24, -1, -1, sizeof(::sensor::Value2Int32Request)},
        {36, -1, -1, sizeof(::sensor::Value4Int32Request)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::sensor::_GestureRequest_default_instance_._instance,
    &::sensor::_Value2DoubleRequest_default_instance_._instance,
    &::sensor::_Value2Int32Request_default_instance_._instance,
    &::sensor::_Value4Int32Request_default_instance_._instance,
};
const char descriptor_table_protodef_sensor_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014sensor.proto\022\006sensor\032\033google/protobuf/"
    "empty.proto\"R\n\016GestureRequest\022\021\n\tdevice_"
    "id\030\001 \001(\t\022\021\n\taction_id\030\002 \001(\t\022\014\n\004op_1\030\003 \001("
    "\005\022\014\n\004op_2\030\004 \001(\005\"W\n\023Value2DoubleRequest\022\021"
    "\n\tdevice_id\030\001 \001(\t\022\021\n\taction_id\030\002 \001(\t\022\014\n\004"
    "op_1\030\003 \001(\001\022\014\n\004op_2\030\004 \001(\001\"V\n\022Value2Int32R"
    "equest\022\021\n\tdevice_id\030\001 \001(\t\022\021\n\taction_id\030\002"
    " \001(\t\022\014\n\004op_1\030\003 \001(\005\022\014\n\004op_2\030\004 \001(\005\"r\n\022Valu"
    "e4Int32Request\022\021\n\tdevice_id\030\001 \001(\t\022\021\n\tact"
    "ion_id\030\002 \001(\t\022\014\n\004op_1\030\003 \001(\005\022\014\n\004op_2\030\004 \001(\005"
    "\022\014\n\004op_3\030\005 \001(\005\022\014\n\004op_4\030\006 \001(\0052\244\002\n\010SensorM"
    "X\022>\n\nSetGesture\022\026.sensor.GestureRequest\032"
    "\026.google.protobuf.Empty\"\000\022H\n\017SetValue2Do"
    "uble\022\033.sensor.Value2DoubleRequest\032\026.goog"
    "le.protobuf.Empty\"\000\022F\n\016SetValue2Int32\022\032."
    "sensor.Value2Int32Request\032\026.google.proto"
    "buf.Empty\"\000\022F\n\016SetValue4Int32\022\032.sensor.V"
    "alue4Int32Request\032\026.google.protobuf.Empt"
    "y\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_sensor_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_sensor_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_sensor_2eproto = {
    false,
    false,
    731,
    descriptor_table_protodef_sensor_2eproto,
    "sensor.proto",
    &descriptor_table_sensor_2eproto_once,
    descriptor_table_sensor_2eproto_deps,
    1,
    4,
    schemas,
    file_default_instances,
    TableStruct_sensor_2eproto::offsets,
    file_level_enum_descriptors_sensor_2eproto,
    file_level_service_descriptors_sensor_2eproto,
};
namespace sensor {
// ===================================================================

class GestureRequest::_Internal {
 public:
};

GestureRequest::GestureRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sensor.GestureRequest)
}
inline PROTOBUF_NDEBUG_INLINE GestureRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::sensor::GestureRequest& from_msg)
      : device_id_(arena, from.device_id_),
        action_id_(arena, from.action_id_),
        _cached_size_{0} {}

GestureRequest::GestureRequest(
    ::google::protobuf::Arena* arena,
    const GestureRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GestureRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, op_1_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, op_1_),
           offsetof(Impl_, op_2_) -
               offsetof(Impl_, op_1_) +
               sizeof(Impl_::op_2_));

  // @@protoc_insertion_point(copy_constructor:sensor.GestureRequest)
}
inline PROTOBUF_NDEBUG_INLINE GestureRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : device_id_(arena),
        action_id_(arena),
        _cached_size_{0} {}

inline void GestureRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, op_1_),
           0,
           offsetof(Impl_, op_2_) -
               offsetof(Impl_, op_1_) +
               sizeof(Impl_::op_2_));
}
GestureRequest::~GestureRequest() {
  // @@protoc_insertion_point(destructor:sensor.GestureRequest)
  SharedDtor(*this);
}
inline void GestureRequest::SharedDtor(MessageLite& self) {
  GestureRequest& this_ = static_cast<GestureRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.device_id_.Destroy();
  this_._impl_.action_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GestureRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GestureRequest(arena);
}
constexpr auto GestureRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(GestureRequest),
                                            alignof(GestureRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GestureRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GestureRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GestureRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GestureRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GestureRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GestureRequest>(), &GestureRequest::ByteSizeLong,
            &GestureRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GestureRequest, _impl_._cached_size_),
        false,
    },
    &GestureRequest::kDescriptorMethods,
    &descriptor_table_sensor_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GestureRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 48, 2> GestureRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sensor::GestureRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 op_2 = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GestureRequest, _impl_.op_2_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(GestureRequest, _impl_.op_2_)}},
    // string device_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GestureRequest, _impl_.device_id_)}},
    // string action_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GestureRequest, _impl_.action_id_)}},
    // int32 op_1 = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GestureRequest, _impl_.op_1_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(GestureRequest, _impl_.op_1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string device_id = 1;
    {PROTOBUF_FIELD_OFFSET(GestureRequest, _impl_.device_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string action_id = 2;
    {PROTOBUF_FIELD_OFFSET(GestureRequest, _impl_.action_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 op_1 = 3;
    {PROTOBUF_FIELD_OFFSET(GestureRequest, _impl_.op_1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 op_2 = 4;
    {PROTOBUF_FIELD_OFFSET(GestureRequest, _impl_.op_2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\25\11\11\0\0\0\0\0"
    "sensor.GestureRequest"
    "device_id"
    "action_id"
  }},
};

PROTOBUF_NOINLINE void GestureRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sensor.GestureRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.device_id_.ClearToEmpty();
  _impl_.action_id_.ClearToEmpty();
  ::memset(&_impl_.op_1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.op_2_) -
      reinterpret_cast<char*>(&_impl_.op_1_)) + sizeof(_impl_.op_2_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GestureRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GestureRequest& this_ = static_cast<const GestureRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GestureRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GestureRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:sensor.GestureRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string device_id = 1;
          if (!this_._internal_device_id().empty()) {
            const std::string& _s = this_._internal_device_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sensor.GestureRequest.device_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string action_id = 2;
          if (!this_._internal_action_id().empty()) {
            const std::string& _s = this_._internal_action_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sensor.GestureRequest.action_id");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int32 op_1 = 3;
          if (this_._internal_op_1() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_op_1(), target);
          }

          // int32 op_2 = 4;
          if (this_._internal_op_2() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_op_2(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:sensor.GestureRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GestureRequest::ByteSizeLong(const MessageLite& base) {
          const GestureRequest& this_ = static_cast<const GestureRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GestureRequest::ByteSizeLong() const {
          const GestureRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:sensor.GestureRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string device_id = 1;
            if (!this_._internal_device_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_device_id());
            }
            // string action_id = 2;
            if (!this_._internal_action_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_action_id());
            }
            // int32 op_1 = 3;
            if (this_._internal_op_1() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_op_1());
            }
            // int32 op_2 = 4;
            if (this_._internal_op_2() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_op_2());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GestureRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GestureRequest*>(&to_msg);
  auto& from = static_cast<const GestureRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sensor.GestureRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_device_id().empty()) {
    _this->_internal_set_device_id(from._internal_device_id());
  }
  if (!from._internal_action_id().empty()) {
    _this->_internal_set_action_id(from._internal_action_id());
  }
  if (from._internal_op_1() != 0) {
    _this->_impl_.op_1_ = from._impl_.op_1_;
  }
  if (from._internal_op_2() != 0) {
    _this->_impl_.op_2_ = from._impl_.op_2_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GestureRequest::CopyFrom(const GestureRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sensor.GestureRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GestureRequest::InternalSwap(GestureRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_id_, &other->_impl_.device_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.action_id_, &other->_impl_.action_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GestureRequest, _impl_.op_2_)
      + sizeof(GestureRequest::_impl_.op_2_)
      - PROTOBUF_FIELD_OFFSET(GestureRequest, _impl_.op_1_)>(
          reinterpret_cast<char*>(&_impl_.op_1_),
          reinterpret_cast<char*>(&other->_impl_.op_1_));
}

::google::protobuf::Metadata GestureRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Value2DoubleRequest::_Internal {
 public:
};

Value2DoubleRequest::Value2DoubleRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sensor.Value2DoubleRequest)
}
inline PROTOBUF_NDEBUG_INLINE Value2DoubleRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::sensor::Value2DoubleRequest& from_msg)
      : device_id_(arena, from.device_id_),
        action_id_(arena, from.action_id_),
        _cached_size_{0} {}

Value2DoubleRequest::Value2DoubleRequest(
    ::google::protobuf::Arena* arena,
    const Value2DoubleRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Value2DoubleRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, op_1_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, op_1_),
           offsetof(Impl_, op_2_) -
               offsetof(Impl_, op_1_) +
               sizeof(Impl_::op_2_));

  // @@protoc_insertion_point(copy_constructor:sensor.Value2DoubleRequest)
}
inline PROTOBUF_NDEBUG_INLINE Value2DoubleRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : device_id_(arena),
        action_id_(arena),
        _cached_size_{0} {}

inline void Value2DoubleRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, op_1_),
           0,
           offsetof(Impl_, op_2_) -
               offsetof(Impl_, op_1_) +
               sizeof(Impl_::op_2_));
}
Value2DoubleRequest::~Value2DoubleRequest() {
  // @@protoc_insertion_point(destructor:sensor.Value2DoubleRequest)
  SharedDtor(*this);
}
inline void Value2DoubleRequest::SharedDtor(MessageLite& self) {
  Value2DoubleRequest& this_ = static_cast<Value2DoubleRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.device_id_.Destroy();
  this_._impl_.action_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Value2DoubleRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Value2DoubleRequest(arena);
}
constexpr auto Value2DoubleRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Value2DoubleRequest),
                                            alignof(Value2DoubleRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Value2DoubleRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Value2DoubleRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Value2DoubleRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Value2DoubleRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Value2DoubleRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Value2DoubleRequest>(), &Value2DoubleRequest::ByteSizeLong,
            &Value2DoubleRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Value2DoubleRequest, _impl_._cached_size_),
        false,
    },
    &Value2DoubleRequest::kDescriptorMethods,
    &descriptor_table_sensor_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Value2DoubleRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 53, 2> Value2DoubleRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sensor::Value2DoubleRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double op_2 = 4;
    {::_pbi::TcParser::FastF64S1,
     {33, 63, 0, PROTOBUF_FIELD_OFFSET(Value2DoubleRequest, _impl_.op_2_)}},
    // string device_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Value2DoubleRequest, _impl_.device_id_)}},
    // string action_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Value2DoubleRequest, _impl_.action_id_)}},
    // double op_1 = 3;
    {::_pbi::TcParser::FastF64S1,
     {25, 63, 0, PROTOBUF_FIELD_OFFSET(Value2DoubleRequest, _impl_.op_1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string device_id = 1;
    {PROTOBUF_FIELD_OFFSET(Value2DoubleRequest, _impl_.device_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string action_id = 2;
    {PROTOBUF_FIELD_OFFSET(Value2DoubleRequest, _impl_.action_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // double op_1 = 3;
    {PROTOBUF_FIELD_OFFSET(Value2DoubleRequest, _impl_.op_1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double op_2 = 4;
    {PROTOBUF_FIELD_OFFSET(Value2DoubleRequest, _impl_.op_2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
    "\32\11\11\0\0\0\0\0"
    "sensor.Value2DoubleRequest"
    "device_id"
    "action_id"
  }},
};

PROTOBUF_NOINLINE void Value2DoubleRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:sensor.Value2DoubleRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.device_id_.ClearToEmpty();
  _impl_.action_id_.ClearToEmpty();
  ::memset(&_impl_.op_1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.op_2_) -
      reinterpret_cast<char*>(&_impl_.op_1_)) + sizeof(_impl_.op_2_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Value2DoubleRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Value2DoubleRequest& this_ = static_cast<const Value2DoubleRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Value2DoubleRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Value2DoubleRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:sensor.Value2DoubleRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string device_id = 1;
          if (!this_._internal_device_id().empty()) {
            const std::string& _s = this_._internal_device_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sensor.Value2DoubleRequest.device_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string action_id = 2;
          if (!this_._internal_action_id().empty()) {
            const std::string& _s = this_._internal_action_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sensor.Value2DoubleRequest.action_id");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // double op_1 = 3;
          if (::absl::bit_cast<::uint64_t>(this_._internal_op_1()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                3, this_._internal_op_1(), target);
          }

          // double op_2 = 4;
          if (::absl::bit_cast<::uint64_t>(this_._internal_op_2()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                4, this_._internal_op_2(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:sensor.Value2DoubleRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Value2DoubleRequest::ByteSizeLong(const MessageLite& base) {
          const Value2DoubleRequest& this_ = static_cast<const Value2DoubleRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Value2DoubleRequest::ByteSizeLong() const {
          const Value2DoubleRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:sensor.Value2DoubleRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string device_id = 1;
            if (!this_._internal_device_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_device_id());
            }
            // string action_id = 2;
            if (!this_._internal_action_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_action_id());
            }
            // double op_1 = 3;
            if (::absl::bit_cast<::uint64_t>(this_._internal_op_1()) != 0) {
              total_size += 9;
            }
            // double op_2 = 4;
            if (::absl::bit_cast<::uint64_t>(this_._internal_op_2()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Value2DoubleRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Value2DoubleRequest*>(&to_msg);
  auto& from = static_cast<const Value2DoubleRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sensor.Value2DoubleRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_device_id().empty()) {
    _this->_internal_set_device_id(from._internal_device_id());
  }
  if (!from._internal_action_id().empty()) {
    _this->_internal_set_action_id(from._internal_action_id());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_op_1()) != 0) {
    _this->_impl_.op_1_ = from._impl_.op_1_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_op_2()) != 0) {
    _this->_impl_.op_2_ = from._impl_.op_2_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Value2DoubleRequest::CopyFrom(const Value2DoubleRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sensor.Value2DoubleRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Value2DoubleRequest::InternalSwap(Value2DoubleRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_id_, &other->_impl_.device_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.action_id_, &other->_impl_.action_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Value2DoubleRequest, _impl_.op_2_)
      + sizeof(Value2DoubleRequest::_impl_.op_2_)
      - PROTOBUF_FIELD_OFFSET(Value2DoubleRequest, _impl_.op_1_)>(
          reinterpret_cast<char*>(&_impl_.op_1_),
          reinterpret_cast<char*>(&other->_impl_.op_1_));
}

::google::protobuf::Metadata Value2DoubleRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Value2Int32Request::_Internal {
 public:
};

Value2Int32Request::Value2Int32Request(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sensor.Value2Int32Request)
}
inline PROTOBUF_NDEBUG_INLINE Value2Int32Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::sensor::Value2Int32Request& from_msg)
      : device_id_(arena, from.device_id_),
        action_id_(arena, from.action_id_),
        _cached_size_{0} {}

Value2Int32Request::Value2Int32Request(
    ::google::protobuf::Arena* arena,
    const Value2Int32Request& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Value2Int32Request* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, op_1_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, op_1_),
           offsetof(Impl_, op_2_) -
               offsetof(Impl_, op_1_) +
               sizeof(Impl_::op_2_));

  // @@protoc_insertion_point(copy_constructor:sensor.Value2Int32Request)
}
inline PROTOBUF_NDEBUG_INLINE Value2Int32Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : device_id_(arena),
        action_id_(arena),
        _cached_size_{0} {}

inline void Value2Int32Request::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, op_1_),
           0,
           offsetof(Impl_, op_2_) -
               offsetof(Impl_, op_1_) +
               sizeof(Impl_::op_2_));
}
Value2Int32Request::~Value2Int32Request() {
  // @@protoc_insertion_point(destructor:sensor.Value2Int32Request)
  SharedDtor(*this);
}
inline void Value2Int32Request::SharedDtor(MessageLite& self) {
  Value2Int32Request& this_ = static_cast<Value2Int32Request&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.device_id_.Destroy();
  this_._impl_.action_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Value2Int32Request::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Value2Int32Request(arena);
}
constexpr auto Value2Int32Request::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Value2Int32Request),
                                            alignof(Value2Int32Request));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Value2Int32Request::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Value2Int32Request_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Value2Int32Request::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Value2Int32Request>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Value2Int32Request::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Value2Int32Request>(), &Value2Int32Request::ByteSizeLong,
            &Value2Int32Request::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Value2Int32Request, _impl_._cached_size_),
        false,
    },
    &Value2Int32Request::kDescriptorMethods,
    &descriptor_table_sensor_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Value2Int32Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 52, 2> Value2Int32Request::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sensor::Value2Int32Request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 op_2 = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Value2Int32Request, _impl_.op_2_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Value2Int32Request, _impl_.op_2_)}},
    // string device_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Value2Int32Request, _impl_.device_id_)}},
    // string action_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Value2Int32Request, _impl_.action_id_)}},
    // int32 op_1 = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Value2Int32Request, _impl_.op_1_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Value2Int32Request, _impl_.op_1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string device_id = 1;
    {PROTOBUF_FIELD_OFFSET(Value2Int32Request, _impl_.device_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string action_id = 2;
    {PROTOBUF_FIELD_OFFSET(Value2Int32Request, _impl_.action_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 op_1 = 3;
    {PROTOBUF_FIELD_OFFSET(Value2Int32Request, _impl_.op_1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 op_2 = 4;
    {PROTOBUF_FIELD_OFFSET(Value2Int32Request, _impl_.op_2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\31\11\11\0\0\0\0\0"
    "sensor.Value2Int32Request"
    "device_id"
    "action_id"
  }},
};

PROTOBUF_NOINLINE void Value2Int32Request::Clear() {
// @@protoc_insertion_point(message_clear_start:sensor.Value2Int32Request)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.device_id_.ClearToEmpty();
  _impl_.action_id_.ClearToEmpty();
  ::memset(&_impl_.op_1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.op_2_) -
      reinterpret_cast<char*>(&_impl_.op_1_)) + sizeof(_impl_.op_2_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Value2Int32Request::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Value2Int32Request& this_ = static_cast<const Value2Int32Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Value2Int32Request::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Value2Int32Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:sensor.Value2Int32Request)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string device_id = 1;
          if (!this_._internal_device_id().empty()) {
            const std::string& _s = this_._internal_device_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sensor.Value2Int32Request.device_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string action_id = 2;
          if (!this_._internal_action_id().empty()) {
            const std::string& _s = this_._internal_action_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sensor.Value2Int32Request.action_id");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int32 op_1 = 3;
          if (this_._internal_op_1() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_op_1(), target);
          }

          // int32 op_2 = 4;
          if (this_._internal_op_2() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_op_2(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:sensor.Value2Int32Request)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Value2Int32Request::ByteSizeLong(const MessageLite& base) {
          const Value2Int32Request& this_ = static_cast<const Value2Int32Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Value2Int32Request::ByteSizeLong() const {
          const Value2Int32Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:sensor.Value2Int32Request)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string device_id = 1;
            if (!this_._internal_device_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_device_id());
            }
            // string action_id = 2;
            if (!this_._internal_action_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_action_id());
            }
            // int32 op_1 = 3;
            if (this_._internal_op_1() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_op_1());
            }
            // int32 op_2 = 4;
            if (this_._internal_op_2() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_op_2());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Value2Int32Request::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Value2Int32Request*>(&to_msg);
  auto& from = static_cast<const Value2Int32Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sensor.Value2Int32Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_device_id().empty()) {
    _this->_internal_set_device_id(from._internal_device_id());
  }
  if (!from._internal_action_id().empty()) {
    _this->_internal_set_action_id(from._internal_action_id());
  }
  if (from._internal_op_1() != 0) {
    _this->_impl_.op_1_ = from._impl_.op_1_;
  }
  if (from._internal_op_2() != 0) {
    _this->_impl_.op_2_ = from._impl_.op_2_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Value2Int32Request::CopyFrom(const Value2Int32Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sensor.Value2Int32Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Value2Int32Request::InternalSwap(Value2Int32Request* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_id_, &other->_impl_.device_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.action_id_, &other->_impl_.action_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Value2Int32Request, _impl_.op_2_)
      + sizeof(Value2Int32Request::_impl_.op_2_)
      - PROTOBUF_FIELD_OFFSET(Value2Int32Request, _impl_.op_1_)>(
          reinterpret_cast<char*>(&_impl_.op_1_),
          reinterpret_cast<char*>(&other->_impl_.op_1_));
}

::google::protobuf::Metadata Value2Int32Request::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Value4Int32Request::_Internal {
 public:
};

Value4Int32Request::Value4Int32Request(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:sensor.Value4Int32Request)
}
inline PROTOBUF_NDEBUG_INLINE Value4Int32Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::sensor::Value4Int32Request& from_msg)
      : device_id_(arena, from.device_id_),
        action_id_(arena, from.action_id_),
        _cached_size_{0} {}

Value4Int32Request::Value4Int32Request(
    ::google::protobuf::Arena* arena,
    const Value4Int32Request& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Value4Int32Request* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, op_1_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, op_1_),
           offsetof(Impl_, op_4_) -
               offsetof(Impl_, op_1_) +
               sizeof(Impl_::op_4_));

  // @@protoc_insertion_point(copy_constructor:sensor.Value4Int32Request)
}
inline PROTOBUF_NDEBUG_INLINE Value4Int32Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : device_id_(arena),
        action_id_(arena),
        _cached_size_{0} {}

inline void Value4Int32Request::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, op_1_),
           0,
           offsetof(Impl_, op_4_) -
               offsetof(Impl_, op_1_) +
               sizeof(Impl_::op_4_));
}
Value4Int32Request::~Value4Int32Request() {
  // @@protoc_insertion_point(destructor:sensor.Value4Int32Request)
  SharedDtor(*this);
}
inline void Value4Int32Request::SharedDtor(MessageLite& self) {
  Value4Int32Request& this_ = static_cast<Value4Int32Request&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.device_id_.Destroy();
  this_._impl_.action_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* Value4Int32Request::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Value4Int32Request(arena);
}
constexpr auto Value4Int32Request::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Value4Int32Request),
                                            alignof(Value4Int32Request));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Value4Int32Request::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Value4Int32Request_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Value4Int32Request::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Value4Int32Request>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Value4Int32Request::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Value4Int32Request>(), &Value4Int32Request::ByteSizeLong,
            &Value4Int32Request::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_._cached_size_),
        false,
    },
    &Value4Int32Request::kDescriptorMethods,
    &descriptor_table_sensor_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Value4Int32Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 52, 2> Value4Int32Request::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::sensor::Value4Int32Request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string device_id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.device_id_)}},
    // string action_id = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.action_id_)}},
    // int32 op_1 = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Value4Int32Request, _impl_.op_1_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.op_1_)}},
    // int32 op_2 = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Value4Int32Request, _impl_.op_2_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.op_2_)}},
    // int32 op_3 = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Value4Int32Request, _impl_.op_3_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.op_3_)}},
    // int32 op_4 = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Value4Int32Request, _impl_.op_4_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.op_4_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string device_id = 1;
    {PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.device_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string action_id = 2;
    {PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.action_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 op_1 = 3;
    {PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.op_1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 op_2 = 4;
    {PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.op_2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 op_3 = 5;
    {PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.op_3_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 op_4 = 6;
    {PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.op_4_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\31\11\11\0\0\0\0\0"
    "sensor.Value4Int32Request"
    "device_id"
    "action_id"
  }},
};

PROTOBUF_NOINLINE void Value4Int32Request::Clear() {
// @@protoc_insertion_point(message_clear_start:sensor.Value4Int32Request)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.device_id_.ClearToEmpty();
  _impl_.action_id_.ClearToEmpty();
  ::memset(&_impl_.op_1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.op_4_) -
      reinterpret_cast<char*>(&_impl_.op_1_)) + sizeof(_impl_.op_4_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Value4Int32Request::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Value4Int32Request& this_ = static_cast<const Value4Int32Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Value4Int32Request::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Value4Int32Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:sensor.Value4Int32Request)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string device_id = 1;
          if (!this_._internal_device_id().empty()) {
            const std::string& _s = this_._internal_device_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sensor.Value4Int32Request.device_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string action_id = 2;
          if (!this_._internal_action_id().empty()) {
            const std::string& _s = this_._internal_action_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "sensor.Value4Int32Request.action_id");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // int32 op_1 = 3;
          if (this_._internal_op_1() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<3>(
                    stream, this_._internal_op_1(), target);
          }

          // int32 op_2 = 4;
          if (this_._internal_op_2() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<4>(
                    stream, this_._internal_op_2(), target);
          }

          // int32 op_3 = 5;
          if (this_._internal_op_3() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<5>(
                    stream, this_._internal_op_3(), target);
          }

          // int32 op_4 = 6;
          if (this_._internal_op_4() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<6>(
                    stream, this_._internal_op_4(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:sensor.Value4Int32Request)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Value4Int32Request::ByteSizeLong(const MessageLite& base) {
          const Value4Int32Request& this_ = static_cast<const Value4Int32Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Value4Int32Request::ByteSizeLong() const {
          const Value4Int32Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:sensor.Value4Int32Request)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string device_id = 1;
            if (!this_._internal_device_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_device_id());
            }
            // string action_id = 2;
            if (!this_._internal_action_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_action_id());
            }
            // int32 op_1 = 3;
            if (this_._internal_op_1() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_op_1());
            }
            // int32 op_2 = 4;
            if (this_._internal_op_2() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_op_2());
            }
            // int32 op_3 = 5;
            if (this_._internal_op_3() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_op_3());
            }
            // int32 op_4 = 6;
            if (this_._internal_op_4() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_op_4());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Value4Int32Request::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Value4Int32Request*>(&to_msg);
  auto& from = static_cast<const Value4Int32Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:sensor.Value4Int32Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_device_id().empty()) {
    _this->_internal_set_device_id(from._internal_device_id());
  }
  if (!from._internal_action_id().empty()) {
    _this->_internal_set_action_id(from._internal_action_id());
  }
  if (from._internal_op_1() != 0) {
    _this->_impl_.op_1_ = from._impl_.op_1_;
  }
  if (from._internal_op_2() != 0) {
    _this->_impl_.op_2_ = from._impl_.op_2_;
  }
  if (from._internal_op_3() != 0) {
    _this->_impl_.op_3_ = from._impl_.op_3_;
  }
  if (from._internal_op_4() != 0) {
    _this->_impl_.op_4_ = from._impl_.op_4_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Value4Int32Request::CopyFrom(const Value4Int32Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sensor.Value4Int32Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Value4Int32Request::InternalSwap(Value4Int32Request* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_id_, &other->_impl_.device_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.action_id_, &other->_impl_.action_id_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.op_4_)
      + sizeof(Value4Int32Request::_impl_.op_4_)
      - PROTOBUF_FIELD_OFFSET(Value4Int32Request, _impl_.op_1_)>(
          reinterpret_cast<char*>(&_impl_.op_1_),
          reinterpret_cast<char*>(&other->_impl_.op_1_));
}

::google::protobuf::Metadata Value4Int32Request::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace sensor
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_sensor_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
