# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x06sensor\x1a\x1bgoogle/protobuf/empty.proto\"R\n\x0eGestureRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\taction_id\x18\x02 \x01(\t\x12\x0c\n\x04op_1\x18\x03 \x01(\x05\x12\x0c\n\x04op_2\x18\x04 \x01(\x05\"W\n\x13Value2DoubleRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\taction_id\x18\x02 \x01(\t\x12\x0c\n\x04op_1\x18\x03 \x01(\x01\x12\x0c\n\x04op_2\x18\x04 \x01(\x01\"V\n\x12Value2Int32Request\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\taction_id\x18\x02 \x01(\t\x12\x0c\n\x04op_1\x18\x03 \x01(\x05\x12\x0c\n\x04op_2\x18\x04 \x01(\x05\"r\n\x12Value4Int32Request\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\taction_id\x18\x02 \x01(\t\x12\x0c\n\x04op_1\x18\x03 \x01(\x05\x12\x0c\n\x04op_2\x18\x04 \x01(\x05\x12\x0c\n\x04op_3\x18\x05 \x01(\x05\x12\x0c\n\x04op_4\x18\x06 \x01(\x05\x32\xa4\x02\n\x08SensorMX\x12>\n\nSetGesture\x12\x16.sensor.GestureRequest\x1a\x16.google.protobuf.Empty\"\x00\x12H\n\x0fSetValue2Double\x12\x1b.sensor.Value2DoubleRequest\x1a\x16.google.protobuf.Empty\"\x00\x12\x46\n\x0eSetValue2Int32\x12\x1a.sensor.Value2Int32Request\x1a\x16.google.protobuf.Empty\"\x00\x12\x46\n\x0eSetValue4Int32\x12\x1a.sensor.Value4Int32Request\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GESTUREREQUEST']._serialized_start=53
  _globals['_GESTUREREQUEST']._serialized_end=135
  _globals['_VALUE2DOUBLEREQUEST']._serialized_start=137
  _globals['_VALUE2DOUBLEREQUEST']._serialized_end=224
  _globals['_VALUE2INT32REQUEST']._serialized_start=226
  _globals['_VALUE2INT32REQUEST']._serialized_end=312
  _globals['_VALUE4INT32REQUEST']._serialized_start=314
  _globals['_VALUE4INT32REQUEST']._serialized_end=428
  _globals['_SENSORMX']._serialized_start=431
  _globals['_SENSORMX']._serialized_end=723
# @@protoc_insertion_point(module_scope)
